### ISSUE TITLE
transform our excel data to a JSON API data 

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/portal-backend#2]

**Comment by vishisht08** [comment]
Hey i am working on this can you please explain a bit more about this.

**Comment by monteirocamis** [comment]
Hi @vishisht08  thank you for your help!!
How can I send you my excel data  please ? 
we have more then 400 lines there

**Comment by monteirocamis** [comment]
@vishisht08  could you make an API to receive this data ? 
i will change the name of this issue

**Comment by monteirocamis** [comment]
@davinyvidal
