### ISSUE TITLE
API JSON | register

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/portal-backend#3]

**Comment by yagizhanNY** [comment]
Hi @monteirocamis, could you give more details about issue? I have experiences about NestJS. I can help you with this issue.

**Comment by monteirocamis** [comment]
Hi @yagizhanNY  , thank you for your time. 
On our JSON , we have: 
{
  "preferenceName": "string",
  "email": "string",
  "birthDate": "2022-10-30T19:59:29.240Z",
  "password": "string",
  "username": "string",
  "rememberToken": false
}

and we need now to include "gender " to use in a checkbox .

**Comment by yagizhanNY** [comment]
Is it done? @monteirocamis

**Comment by monteirocamis** [comment]
Hey @yagizhanNY  yes =(
I am sorry I am going to close this issue 

Let us know if you have some suggestions to improve our  back end!!
we can open issues
